# Site information
site_name: 'Will Christerson'
site_description: A site displaying some projects that I have created
site_author: 'Will Christerson'

# Copyright
copyright: 'Built by <a href="https://github.com/wbchristerson">Will Christerson</a> &copy 2021'

nav:
    - Home: index.md
    - Projects:
        - Disaster Reporter: DisasterReporter.md
        - Neural Network Flower Classifier: FlowerClassifier.md
        - Maximum Matchings: MaximumMatchings.md
        - Neighborhood Map: NeighborhoodMap.md
        - Mobile Flashcards: MobileFlashcards.md
        - Readables: Readables.md
        - MyReads: MyReads.md
        - Mathematical Database: MathematicalDatabase.md
        - Frogger: Frogger.md
        - Matching Game: MatchingGame.md
        - Pixel Art: PixelArt.md

# Repository
repo_name: 'wbchristerson/pfs'
repo_url: 'https://github.com/wbchristerson/pfs'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/wbchristerson'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/william-christerson/'

theme:
  name: 'material'
  language: 'en'
  # favicon: "https://user-images.githubusercontent.com/297678/29892310-03e92256-8d83-11e7-9b58-986dcb6f702e.png"
  palette:
    primary: 'light blue'
    accent: 'indigo'
  font:
    text: 'Roboto'
    # code: 'Roboto Mono'
  logo:
    icon: 'import_contacts'
